apiVersion: v1
kind: Service
metadata:
  name: sonar-svc
spec:
  type: NodePort
  ports:
    - port: 8000 #“nodePort” forwards to this “port”
      targetPort: 9000 #It redirects the traffic received on “Port” to “targetPort” 
      nodePort: 30001 #traffic is received on “nodePort”
  selector:
    app: sonar-svc