apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-api-deployment
spec:
  template:
    metadata:
      labels:
        app: employee-svc
    spec:
      containers:
        - name: employee-api-container
          image: ramonrezende/employee-api:5.0.0
          ports:
            - containerPort: 8080
            - containerPort: 9090
          envFrom:
            - configMapRef:
                name: employee-configmap
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 60
            periodSeconds: 40
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 2
  replicas: 2
  selector:
    matchLabels:
      app: employee-svc
